grammar ggq.GGQ with org.eclipse.xtext.common.Terminals

import "http://www.example.org/modeling" 
import "http://www.eclipse.org/emf/2002/Ecore" as ecore

GraphQueryRule returns GraphQuery:
	{GraphQuery}
	(containedVertices+=Vertex)*
	(containedEdges+=Edge)*;

Vertex returns Vertex:
	{Vertex}
	id=ID ':' type=[ecore::EClass|QualifiedName];
	
Edge returns Edge:
	source=[Vertex|ID] '->' target=[Vertex|ID] ':' type=[ecore::EReference|QualifiedName];
	
QualifiedName:
	ID ('.'ID) *;
